spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: apiGateway

server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
resilience4j.circuitbreaker:
  instances:
    fooClient:
      registerHealthIndicator: true
      slidingWindowSize: 50
      automaticTransitionFromOpenToHalfOpenEnabled: true
      eventConsumerBufferSize: 10
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
resilience4j:
  retry:
    instances:
      retryApi:
        maxAttempts: 5
        waitDuration: 3s
        maxRetryAttempts: 5
  #mybatis-plus:
  #  mapper-locations: classpath:/mapper/xml/*.xml
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #JSON RETURN VALUE NULL EMPTY V#ALUES
  #  spring.main.allow-bean-definition-overriding=true
  #spring.application.name=api-gateway
#Logging.level.root=INFO
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
#logging.level.org.springframework.cloud.gateway=TRACE