spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: schoolModule
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fasystem_main?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
  jackson:
    default-property-inclusion: ALWAYS
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8085
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
mybatis-plus:
  check-config-location: false
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
